---

- name: Ensure Python version 2.7
  command: python -V
  sudo: yes
  changed_when: False
  register: python_version

- name: Find default pip executable
  command: which pip
  register: default_pip
  changed_when: False
  sudo: yes

- name: Set name of default pip executable
  set_fact:
    pip_executable: "{{ default_pip.stdout }}"

- include: my-python.yml
  when: python_version.stderr|match('Python 2.6\..*') and ansible_distribution == "CentOS"
