---

- name: Upload server wheel
  copy:
    src: server-{{ server_version }}-py2.py3-none-any.whl
    dest: /tmp/
  register: wheel_uploaded

- name: Install server wheel
  pip:
    name: "/tmp/server-{{ server_version }}-py2.py3-none-any.whl"
    executable: "{{ pip_executable }}"
  sudo: yes
  when: wheel_uploaded|changed

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: debian.yml
  when: ansible_os_family == "Debian"

- name: Set supervisor config for the server
  template:
    src: server.ini.j2
    dest: "{{ supervisor_conf_dir }}/server.{{ supervisor_conf_ext }}"
  register: server_config
  sudo: yes

- name: Ensure supervisor sees the config for server
  shell: kill -HUP $(cat /var/run/supervisord.pid)
  sudo: yes
  when: server_config|changed

- name: Ensure pymongo is installed
  pip:
    name: pymongo
    state: latest
    executable: "{{ pip_executable }}"
  sudo: yes

- name: Make sure the analytics server is started
  supervisorctl:
    name: analytics_server
    state: present
    supervisorctl_path: "{{ supervisor_ctl }}"
  sudo: yes
