---

- name: Install supervisor in Redhat
  pip:
    name: supervisor
    executable: /usr/local/python/bin/pip
  sudo: yes

- name: Set name of supervisor in Redhat
  set_fact:
    supervisor_conf_dir: /etc/supervisord.d
    supervisor_conf_ext: ini
    supervisor_service: supervisord
    supervisor_ctl: /usr/local/python/bin/supervisorctl
  when: ansible_os_family == 'RedHat'

- name: Ensure config directory for supervisor exists
  file: name=/etc/supervisord.d state=directory
  sudo: yes

- name: Ensure config file for supervisor
  copy:
    src: supervisor.conf
    dest: /etc/supervisord.conf
  sudo: yes

- name: Check there is a supervisor running
  command: pgrep -lf supervisor
  ignore_errors: yes
  register: supervisor_pid
  changed_when: supervisor_pid|failed

- name: Ensure supervisor log directory
  file: path=/var/log/supervisor state=directory
  sudo: yes

- name: Start Redhat supervisor if necessary
  command: /usr/local/python/bin/supervisord -c /etc/supervisord.conf
  sudo: yes
  when: supervisor_pid|failed
